// SPDX-FileCopyrightText: 2026 Guillermo Themsel
// SPDX-License-Identifier: GPL-3.0-or-later

package dev.themselg.jellymusic.ui.theme

import androidx.compose.animation.animateColorAsState
import androidx.compose.animation.core.tween
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.ColorScheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.dynamicDarkColorScheme
import androidx.compose.material3.dynamicLightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import com.materialkolor.PaletteStyle
import com.materialkolor.rememberDynamicColorScheme
import dev.themselg.jellymusic.data.prefs.ColorMode
import dev.themselg.jellymusic.data.prefs.DarkMode
import dev.themselg.jellymusic.data.prefs.ThemeSettings

/**
 * Root theme. Picks the Material 3 [ColorScheme] from [settings]:
 *  - STATIC    → fixed brand palette
 *  - SYSTEM    → Material You from the wallpaper (Android 12+, always available at minSdk 31)
 *  - ALBUM_ART → scheme generated by MaterialKolor from [seedColor] (the playing album's art)
 *
 * Whatever the source, the resulting colors are animated so transitions (e.g. switching
 * to a track with very different cover art) cross-fade smoothly instead of snapping.
 */
@Composable
fun AppTheme(
    settings: ThemeSettings,
    seedColor: Color?,
    content: @Composable () -> Unit,
) {
    val context = LocalContext.current
    val isDark = when (settings.darkMode) {
        DarkMode.SYSTEM -> isSystemInDarkTheme()
        DarkMode.LIGHT -> false
        DarkMode.DARK -> true
    }

    val baseScheme: ColorScheme = when (settings.colorMode) {
        ColorMode.STATIC -> if (isDark) StaticDarkColors else StaticLightColors
        ColorMode.SYSTEM -> if (isDark) dynamicDarkColorScheme(context) else dynamicLightColorScheme(context)
        ColorMode.ALBUM_ART -> rememberDynamicColorScheme(
            seedColor = seedColor ?: DefaultSeed,
            isDark = isDark,
            // AMOLED is applied uniformly below via toAmoled(), so keep it off here.
            isAmoled = false,
            style = PaletteStyle.TonalSpot,
        )
    }

    val themedScheme = if (settings.amoledBlack && isDark) baseScheme.toAmoled() else baseScheme

    MaterialTheme(
        colorScheme = themedScheme.animated(),
        typography = AppTypography,
        content = content,
    )
}

private fun ColorScheme.toAmoled(): ColorScheme = copy(
    background = Color.Black,
    surface = Color.Black,
    surfaceContainerLowest = Color.Black,
    surfaceContainerLow = Color(0xFF0A0A0A),
)

/** Animate the visible color roles so scheme changes cross-fade. */
@Composable
private fun ColorScheme.animated(): ColorScheme {
    val spec = tween<Color>(durationMillis = 450)

    @Composable
    fun anim(target: Color, label: String) = animateColorAsState(target, spec, label = label).value

    return copy(
        primary = anim(primary, "primary"),
        onPrimary = anim(onPrimary, "onPrimary"),
        primaryContainer = anim(primaryContainer, "primaryContainer"),
        onPrimaryContainer = anim(onPrimaryContainer, "onPrimaryContainer"),
        secondary = anim(secondary, "secondary"),
        onSecondary = anim(onSecondary, "onSecondary"),
        secondaryContainer = anim(secondaryContainer, "secondaryContainer"),
        onSecondaryContainer = anim(onSecondaryContainer, "onSecondaryContainer"),
        tertiary = anim(tertiary, "tertiary"),
        tertiaryContainer = anim(tertiaryContainer, "tertiaryContainer"),
        background = anim(background, "background"),
        onBackground = anim(onBackground, "onBackground"),
        surface = anim(surface, "surface"),
        onSurface = anim(onSurface, "onSurface"),
        surfaceVariant = anim(surfaceVariant, "surfaceVariant"),
        onSurfaceVariant = anim(onSurfaceVariant, "onSurfaceVariant"),
        surfaceTint = anim(surfaceTint, "surfaceTint"),
        surfaceContainerLowest = anim(surfaceContainerLowest, "surfaceContainerLowest"),
        surfaceContainerLow = anim(surfaceContainerLow, "surfaceContainerLow"),
        surfaceContainer = anim(surfaceContainer, "surfaceContainer"),
        surfaceContainerHigh = anim(surfaceContainerHigh, "surfaceContainerHigh"),
        surfaceContainerHighest = anim(surfaceContainerHighest, "surfaceContainerHighest"),
        outline = anim(outline, "outline"),
        outlineVariant = anim(outlineVariant, "outlineVariant"),
    )
}
